USE test;
CREATE TABLE IF NOT EXISTS SiteInfoDe(
	s_id INT NOT NULL,
    s_name VARCHAR(50) NOT NULL,
    s_description VARCHAR(800) NOT NULL,
    
    PRIMARY KEY (s_id)
);

INSERT INTO SiteInfoDe(
	s_id, s_name, s_description
)Values
	(1, "Akropolis", "Die Akropolis in Athen ist wohl das bekannteste Bauwerk des antiken Griechenlands. Diese einzigartigen Gebäude wurden zwischen 464 v. Chr und 406 v. Chr auf einem 156 Meter hohen Felsen erbaut. Zu den Gebäuden gehören, das Erechtheion, der Niketempel, die Propyläen und der Parthenon-Tempel, in dem eine Statue der Göttin Athene gestanden haben soll. Eine Akropolis war in der Antike zumeist eine auf dem höchsten Teil der Stadt gelegene Befestigung. Auch die Akropolis von Athen hatte zunächst vorrangig eine Verteidigungsfunktion inne."),
    (2, "Parthenon", "Der prachtvolle Parthenon ist der zentrale Tempel der Akropolis in der griechischen Hauptstadt Athen und eines der bekanntesten Bauwerke der Welt. Einige Originalteile wurden entfernt und sind heute im Akropolis-Museum zu besichtigen. Der Parthenon ist der Haupttempel der Akropolis in der griechischen Hauptstadt Athen und befindet sich seit fast 2.500 Jahren im Zentrum der prachtvollen Tempelanlage. Gemeinsam mit dem Gesamtkomplex der Akropolis ist er Teil des UNESCO-Weltkulturerbes."),
    (3, "Olympieion", "Das Olympieion (auch Tempel des Olympischen Zeus) in Athen war der größte Tempel im antiken Griechenland. Der Bau geht auf das 6. Jahrhundert v. Chr. zurück, wurde aber erst unter dem römischen Kaiser Hadrian im 2. Jahrhundert vollendet. Das Olympieion befindet sich rund 500 m östlich der Akropolis. Das Olympieion war ein korinthischer Dipteros. Mit einer Grundfläche von 108 x 41 Metern war er mehr als doppelt so groß wie der Parthenon. Ursprünglich besaß das Olympieion 104 über 17 m hohe korinthische Säulen, von denen heute 15 wieder aufgerichtet sind."),
    (4, "Plaka", "Unterhalb der Akropolis befindet sich Athens schönster Stadtteil und zugleich beliebtes Einkaufsviertel, die Plaka. Sie besteht aus einem alten, labyrinthartigen Gewirr an Gassen. Hier befinden sich unzählige kleine Geschäfte, Souvenirläden, Restaurants, Bars, Cafés und Tavernen. Dieser Stadtteil, der sich im Laufe der letzten Jahre zu einem der teuersten der griechischen Metropole entwickelt hat, ist nicht nur bei den Athenern beliebt. Scharenweise zieht Plaka auch in jedem Jahr die Touristen an. Vor allem an Wochenenden ist hier sehr viel los."),
    (5, "Syntagma-Platz", "Der Syntagma-Platz ist der bedeutendste Platz Athens; er ist ständig gefüllt mit Anwohnern und Touristen gleichermaßen. Der Platz grenzt an seiner östlichen Seite an das Hellenische Parlamentsgebäude an, welches ursprünglich der königliche Palast. Er ist Dreh- und Angelpunkt der öffentlichen Verkehrsmittel der Stadt - Busse, Straßenbahnen und auch die Metro halten hier. Der Platz ist mit einem zentralen Wasserspiel, mehreren Statuen und zwei Grasflächen mit vielen Bäumen geschmückt, die perfekt zum Entspannen im Schatten geeignet sind."),
    (6, "Agora", "Die Agora war das geschäftliche, soziale und politische Herzstück des antiken Athen. Sie war das Zentrum des Alltags – hierher kamen die Menschen zum Einkaufen, zur Unterhaltung und zu sozialen Aktivitäten. Die Ausgrabungen begannen im frühen 20. Jahrhundert und enthüllten eine Vielzahl von Tempeln, Stoen, Altaren und sogar einen Konzertsaal. Gerichte tagten hier, und Philosophen sprachen vor den Menschen, die hier einkauften und über die Neuigkeiten des Tages diskutierten. Auch Schulen und Sporteinrichtungen standen zur Verfügung."),
	(7, "Erechtheion", "The Erechtheion originated long after the establishment of the Propylaea and the Parthenon in the period from 421 to 406 BC. As with the Temple of Athena, the uneven structure of the floor called for a complex construction on two levels. However, the necessity of being creative is demonstrated by the masterly aesthetics of a form of design that is second to none in antiquity. Analogous to the Propylaeans, however, the execution of the Erechtheum in its perfection did not correspond to the original plan"),
	(8, "Lycabettus", "Der Lycabettus ist der Stadtberg Athens und mit 277 Metern die höchste Erhebung in der Stadt. Von hier kann man alle Sehenswürdigkeiten von oben sehen und du begreift die Ausmasse von Athen erst so richtig. Die Stadt mutet nämlich nicht so gross an, wenn man mitten drin steckt, als wenn man über sie hinwegsehen kann und das bis zum Meer. Die Aussicht hier ist einfach fantastisch und unvergleichlich. Auf dem Gipfel findet man eine kleine Kapelle, ein eher teureres Restaurant und eine Aussichtsplattform. Interessanterweise ist der Lycabettus aber nicht so von Touristen überlaufen wie andere Sehenswürdigkeiten."),
    (9, "Odeon des Herodes Atticus", "Herodes Atticus war ein aristokratischer und wohlhabender Grieche, der mehrere große Bauprojekte im alten Athen finanzierte, darunter das Odeon, das er 161 v. Chr. in Gedenken an seine Frau in Auftrag gab. Das Odeon befindet sich am Fuße der südlichen Hänge der Akropolis und diente einst als Konzertsaal mit 32 Sitzreihen im Halbkreis, einer Bühne und einer Holzdecke für die Akustik. Hier kamen 5000 Menschen unter, während die dreistöckige Fassade des Odeons mit vier großen Bögen ausgestattet und mit Statuen der Musen dekoriert war."),
    (10, "Wabi Sabi", "Das Wabi Sabi ist eines der besten Restaurants Athens wenn es um das Thema Chinesisches Essen in Griechenland geht. Von Sushi über gebratene Ente bis hin zu feinsten Reisnudeln wird hier alle geboten und das alles auch noch zu einem unschlagbaren Preis, wie sie ihn in Athen kein zweites Mal finden werden! Bester Fisch aus Großteiles lokalem Fischfang hat bisher noch jeden unserer währten Besucher überzeugt. Wir haben jeden Tag im Jahr geöffnet für Sie von 9.00 Uhr bis 23.00 Uhr außer am chinesischen Neujahr."),
    (11, "Dionysostheater", "Das Dionysostheater, am Fuße des südlichen Abhangs der Akropolis, ist die Geburtsstätte des europäischen Theaters. Bereits im Jahre 534 v. Chr. wurden hier berühmte griechische Tragödien und Komödien aufgeführt. Viele Stücke von berühmten griechischen Schriftstellern wurden hier während den Dionysien, einem Theaterfestival zu Ehren des Gottes Dionysos, nach dem das Theater benannt wurde, uraufgeführt. Dionysos galt als der Gott des Theaters."),
    (12, "Nationalgarten", "Der Nationalgarten, die größte grüne Oase im Athener Zentrum ist ideal für einen Spaziergang zwischen den geräuschvollen Boulevards. Er wurde im Jahr 1839 gestaltet und war der Garten des Palastes der ersten Könige Griechenlands, wo heute das griechische Parlament steht. Der Nationalgarten hat auch Seen mit Enten, Skulpturen, eine originelle Sonnenuhr, verstreute Altertümer, Botanisches Museum, Spielplatz, Spielbibliothek und ein malerisches traditionelles Café. Er ist jeden Tag vom Sonnenaufgang bis Sonnenuntergang geöffnet."),
    (13, "Tempel der Athena", "Der Alte Athena-Tempel war bis zur Zerstörung durch die Perser im Jahr 480 v. Chr. der Kultbau für Athena Polias, die Stadtgöttin Athens auf der Akropoliss. An zentraler Stelle auf der Akropolis gelegen, erhob er sich auf den Resten einer mykenischen Palastanlage. Neben den Fundamenten wurden zahlreiche Bauglieder dorischer Ordnung gefunden, die mit dem Tempel und seinen verschiedenen Bauphasen in Verbindung gebracht werden. Die Fundamente waren aus unterschiedlichen Materialien und in unterschiedlicher Technik verlegt."),
    (14, "Akropolismuseum", "Das Neue Akropolis-Museum lässt das ausgediente Museum auf dem Felsplateau der Akropolis völlig in Vergessenheit geraten. Bereits während der feierlichen Eröffnung am 20. Juni 2009 wurde international ein einhelliger Sturm der Begeisterung ausgelöst. Das Neue Akropolis-Museum hat einen Platz in der Riege der besten Museen weltweit eingenommen. Die Architektur und Konzeption des neuen Bauwerks, die Atmosphäre aus Antike und Moderne und die technische Umsetzung der Präsentation der Exponate suchen Ihresgleichen."),
    (15, "Hadrianstor", "Der den Athenern zugeneigte Kaiser Hadrian gründete einst ein Stadtviertel an der östlichen Grenze des alten Athens. Zu seinen Ehren gaben die Athener diesem den Namen Adrianopolis und errichteten in den Jahren 131 bis 132 nach Christus ein Tor aus pentelischem Marmor, das Hadrianstor, das von der alten Stadt in die neue überleitete. Das Tor, das sich nur unweit des Tempels des Olympischen Zeus befindet, blieb bis in die Neuzeit intakt und hervorragend erhalten. Es zählt heutzutage zu den bekanntesten und meistfotografierten Bauwerken der Stadt."),
    (16, "KFC", "KFC bietet das leckerste Hühnchen der Welt mit schnellem Service in einer freundlichen und modernen Umgebung! 1993 kreierte Colonel Harland Sanders das ursprüngliche Rezept aus Kentucky, präsentierte die geheime Mischung aus 11 Kräutern und Gewürzen und eröffnete ein kleines Restaurant namens Sanders . Dort begann er, Hühnchen mit dem berühmten Rezept aus 11 Kräutern und Gewürzen zu kochen. So wurden KFC-Hühnchen so berühmt. Heute zählt KFC zu den größten Fast-Food-Ketten der Welt.")
;
    
CREATE TABLE IF NOT EXISTS SiteInfoEn(
	s_id INT NOT NULL,
    s_name VARCHAR(50) NOT NULL,
    s_description VARCHAR(800) NOT NULL,
    
    PRIMARY KEY (s_id)
);

INSERT INTO SiteInfoEn(
	s_id, s_name, s_description
)Values    
	(1, "Acropolis", "The Acropolis in Athens is probably the most famous building of ancient Greece. The unique buildings were built between 464 B.C. and 406 B.C. on a 156 metre high rock. To the buildings belong, the Erechtheion, the Nike temple, the Propyläen and the Parthenon temple, in which a statue of the goddess Athene is said to have stood. In ancient times, an acropolis was usually a fortification situated on the highest part of the city. The Acropolis of Athens also had a defensive function."),
    (2, "Parthenon", "The splendid Parthenon is the central temple of the Acropolis in the Greek capital Athens and one of the most famous buildings in the world. Some original parts have been removed and can now be seen in the Acropolis Museum. The Parthenon is the main temple of the Acropolis in the Greek capital Athens and has been in the centre of the magnificent temple complex for almost 2,500 years. Together with the whole complex of the Acropolis it is part of the UNESCO World Heritage Site."),
    (3, "Olympieion", "The Olympieion (also Temple of Olympic Zeus) in Athens was the largest temple in ancient Greece. The construction dates back to the 6th century BC, but was only completed under the Roman Emperor Hadrian in the 2nd century. The Olympieion is located about 500 m east of the Acropolis. The Olympieion was a Corinthian Dipteros. With a base area of 108 x 41 metres, it was more than twice the size of the Parthenon. Originally, the Olympieion had 104 Corinthian columns over 17 m high, 15 of which are now upright again.  "),
    (4, "Plaka", "Below the Acropolis is Athens most beautiful district and at the same time a popular shopping district, the Plaka. It consists of an old maze of alleys. There are countless small shops, souvenir shops, restaurants, bars, cafés and taverns. This district, which has become one of the most expensive in the Greek metropolis in recent years, is not only popular among the Athenians. Plaka also attracts many tourists every year. Especially on weekends there is a lot going on here."),
    (5, "Syntagma-Square", "Syntagma Square is the most important square in Athens; it is constantly filled with residents and tourists. The square borders on its eastern side on the Hellenic Parliament Building, which was originally the Royal Palace. It is the hub of the city's public transportation - buses, trams and the metro stop here. The square is decorated with a central water feature, several statues and two grassy areas with many trees that are perfect for relaxing in the shade."),
    (6, "Agora", "The Agora was the business, social and political heart of ancient Athens. It was the center of everyday life - here people came for shopping, entertainment and social activities. The excavations began in the early 20th century and revealed a multitude of temples, jumbos, altars and even a concert hall. Courts were meeting here, and philosophers were speaking to the people who were shopping here and discussing the news of the day. Schools and sports facilities were also available."),
	(7, "Erechtheion", "The Erechtheion was built long after the construction of the Propylaea and the Parthenon between 421 and 406 BC. As with the Temple of Athena, the uneven structure of the ground required an elaborate construction on two levels. The fact that necessity makes invention, however, is proven by the masterly aesthetics of a form of design that is unparalleled in antiquity. Analogous to the Propyläen, however, the execution of the Erechtheion did not correspond in its perfection to the original planning."),
	(8, "Lycabettus", "The Lycabettus is the city-mountain of Athens and with 277 meters the highest elevation in the city. From here you can see all the sights from above and you will really understand the dimensions of Athens. The city doesn't seem as big when you're in the middle of it as when you can overlook it and that up to the sea. The view here is simply fantastic and incomparable. At the top, there is a small chapel, a more expensive restaurant and a viewing platform. Interestingly, the Lycabettus is not as crowded with tourists as other sightseeings."),
    (9, "Odeon of Herodes Atticus", "Herodes Atticus was an aristocratic and wealthy Greek who financed several major construction projects in ancient Athens, including the Odeon, which he commissioned in 161 BC in memory of his wife. Located at the foot of the southern slopes of the Acropolis, the Odeon once served as a concert hall with 32 rows of semi-circular seats, a stage and a wooden ceiling for acoustics. It accommodated 5000 people, while the three-storey façade of the Odeon had four large arches and was decorated with statues of the Muses."),
    (10, "Wabi Sabi", "The Wabi Sabi is one of the best restaurants when it comes to Chinese food in Greece. From sushi and roasted duck to the finest rice noodles, you'll find it all here at an unbeatable price, you won't find anywhere else in Athens! Best fish from mostly local fishing has so far convinced every one of our visitors. We are open for you every day of the year from 9.00 a.m. to 11.00 p.m. except at the Chinese New Year."),
    (11, "Dionysostheatre", "The Dionysostheatre, at the foot of the southern slope of the Acropolis, is the birthplace of European theatre. Famous Greek tragedies and comedies were performed here back in 534 BC. Many plays by famous Greek writers were premiered here during Dionysus, a theatre festival in honour of the god Dionysus, after whom the theatre was named. Dionysus was considered the god of theatre."),
    (12, "National Garden", "The National Garden, the largest green oasis in the centre of Athens, is ideal for a stroll between the noisy boulevards. It was designed in 1839 and was the first kings garden, where today the Greek Parliament stands. The National Garden also has lakes with ducks, sculptures, an original sundial, scattered antiquities, botanical museum, playground, games library and a picturesque traditional café. It is open every day from sunrise to sunset."),
    (13, "Tempel of Athena", "Until it was destroyed by the Persians in 480 BC, the Old Athena Temple was the cult building for Athena Polias, the city goddess of Athens on the Acropoliss. Located centrally on the Acropolis, it rose on the remains of a Mycenaean palace complex. In addition to the foundations, numerous Doric-order structural elements were found, which are associated with the temple and its various construction phases. The foundations were made of different materials and were laid in different techniques."),
    (14, "Acropolismuseum", "The New Acropolis Museum has completely forgotten the old museum on the rocky plateau of the Acropolis. Already during the ceremonial opening on 20 June 2009 a unanimous storm of enthusiasm was triggered internationally. The New Acropolis Museum has taken its place among the best museums in the world. The architecture and conception of the new building, the atmosphere from antiquity and modernity and the technical implementation of the presentation of the exhibits are second to none."),
    (15, "Hadrianstor", "The emperor Hadrian, who loved the Athenians, once founded a district on the eastern border of ancient Athens. In his honour the Athenians gave it the name Adrianopolis and in the years 131 to 132 after Christ, they built a gate from pentelic marble, the Hadrian gate, which led from the old city into the new one. The gate, which is not far from the temple of the Olympic Zeus, remained intact until modern times and was excellently preserved. Today it is one of the most famous and most photographed buildings in the city."),
    (16, "KFC", "KFC offers the tastiest chicken in the world with fast service in a friendly and modern environment! In 1993 Colonel Harland Sanders created the original Kentucky recipe, presented the secret blend of 11 herbs and spices and opened a small restaurant called Sanders. There he started cooking chicken with the famous recipe of 11 herbs and spices. That's how KFC chicken became so famous. Today KFC is one of the largest fast food chains in the world.")
;


CREATE TABLE IF NOT EXISTS Sites(
	s_id INT NOT NULL AUTO_INCREMENT,
    s_address VARCHAR(100) NOT NULL,
    s_x DOUBLE NOT NULL,
    s_y DOUBLE NOT NULL,
    s_image1 VARCHAR(50) NOT NULL,
    s_image2 VARCHAR(50) NOT NULL,
    s_image3 VARCHAR(50) NOT NULL,
    
    PRIMARY KEY (s_id)
);

INSERT INTO Sites(
	s_address, s_x, s_y, s_image1, s_image2, s_image3
)Values
	("Athen 105 58", 37.971536, 23.7257316, "akropolis1.jpg", "akropolis2.jpg", "akropolis3.jpg"),
    ("Athen 105 58", 37.9715202, 23.726709, "parthenon1.jpg", "parthenon2.jpg", "parthenon3.png"),
    ("Athen 105 57", 37.9692945, 23.7330792, "olympieion1.jpg", "olympieion2.jpg", "olympieion3.jpg"),
    ("Plaka", 37.9724132, 23.7300487, "plaka1.jpg", "plaka2.jpg", "plaka3.jpg"),
    ("Pl. Sintagmatos, Athen 105 63", 37.9755383, 23.7348455, "syntagma_platz1.jpg" ,"syntagma_platz2.jpg" ,"syntagma_platz3.jpg"),
    ("Adrianou 24, Athen 105 55", 37.9746468, 23.7219594, "agora1.jpg", "agora2.jpg","agora3.jpg"),
	("Athen 105 58", 37.9720758, 23.7265143, "erechtheion1.jpg", "erechtheion2.jpg", "erechtheion3.jpg"),
	("Lykabettus", 37.9818057, 23.7430266, "lycabettus1.jpg", "lycabettus2.jpg","lycabettus3.jpg"),
    ("Areopagitou Dionisiou, Athen 105 55", 37.970798, 23.7245708, "odeon_des_herodes_atticus1.jpg", "odeon_des_herodes_atticus2.jpg", "odeon_des_herodes_atticus3.jpg"),
    ("Emmanouil Benaki 9, Athen 106 78", 37.9836115, 23.7309452, "wabi_sabi1.jpg" ,"wabi_sabi2.jpg","wabi_sabi3.jpg"),
    ("Mitseon 25, Athina 117 42", 37.9703709, 23.7278924, "dionysostheater1.jpg", "dionysostheater2.jpg", "dionysostheater3.jfif"),
    ("Leoforos Vasilisis Amalias 1, Athina 105 57", 37.9728375, 23.7374876, "nationalgarten1.jpg", "nationalgarten2.jpg", "nationalgarten3.jpg"),
    ("Acropolis, Dionysiou Areopagitou, Athina 105 58", 37.9715173, 23.7248735, "tempel_der_athena1.jpg", "tempel_der_athena2.jpg", "tempel_der_athena3.jpg"),
    ("Dionysiou Areopagitou 15, Athina 117 42", 37.9684444, 23.7285321, "akropolismuseum1.jpg", "akropolismuseum2.jpg","akropolismuseum3.jpg"),
    ("Leoforos Vasilisis Amalias 50, Athina 105 58", 37.9701893, 23.7320125, "hadrianstor1.jfif", "hadrianstor2.jpg", "hadrianstor3.jpg"),
    ("Mitropoleos 3, Athina 105 57", 37.9750144, 23.7337011, "kfc1.jpg", "kfc2.jpg", "kfc3.jpg")
;